# Generated by Django 4.2.27 on 2026-03-19 16:18

from django.db import migrations, models
import storage.models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=storage.models.preview_directory_path),
        ),
    ]
