# Generated by Django 4.2.27 - Data migration to hash existing plaintext passwords

from django.db import migrations
from django.contrib.auth.hashers import make_password


def hash_existing_passwords(apps, schema_editor):
    """将已有的明文分享密码转换为哈希存储"""
    FileShare = apps.get_model('share', 'FileShare')
    
    for share in FileShare.objects.exclude(password=''):
        # 检查是否已经是哈希格式（以算法前缀开头）
        if not share.password.startswith('pbkdf2_') and \
           not share.password.startswith('bcrypt') and \
           not share.password.startswith('argon2') and \
           not share.password.startswith('scrypt'):
            # 是明文密码，进行哈希
            share.password = make_password(share.password)
            share.save(update_fields=['password'])


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_alter_fileshare_password'),
    ]

    operations = [
        migrations.RunPython(hash_existing_passwords, reverse_code=migrations.RunPython.noop),
    ]